### ISSUE TITLE
Strange dungeon issue

### ISSUE THREAD

**Issue by Creeperman8362** [SteveKunG/More-Planets#100]
When I was exploring dungeons, I noticed that all ancient chests were empty, and some spawners were replaced with pig spawners, but others weren't. I know for sure that this was not due to world corruption, since I found those dungeons on other planets and visited them the first time by going to the exact coordinates, so I was generating the new chunks on those planets. I cant provide my world save, as I have already harvested the spawners using another mod. 

I have tested out in a seperate world, and it works, but all dungeons generated in my survival world are glitched. I have also copied my world and tested it with another known dungeon and that one works. It may seem like my world got corrupted, but there's no way it could've been corrupted if the chunks were generated when I first visited the dungeon on that planet.

Seed is "powerball jackpot" and the coordinates for the dungeons I explored were:
x1198
z-7374
		
x1357
z-6775

**Comment by SteveKunG** [comment]
More Planets version?

**Comment by Creeperman8362** [comment]
1.3.0. I also have more information. In the OP, I stated that it worked. I did the same today and it is broken. Yesterday, I explored Nibiru in survival and the dungeons at the 2 coordinates listed were broken but I copied the world and went to the dungeon at x-67 z3215. That one worked. 

Today, I copied my survival world again and went to Diona, and went to both dungeons listed in OP, and they were broken. The game output shows nothing unusual. I also checked the launcher log, and nothing. fml-client-latest.log lists a bunch of ID mismatches, but I checked my stuff in my world, still there. Also on Diona, all the blocks were intact. The location of the dungeon has never been visited in that world. I have also deleted more planets ASM, as you say it is no longer needed.

I have zipped up my world and provided it for download. I did not pack my mods folder with it, and the player is currently inside the Diona dungeon, coordinates listed in OP. If you need my mods folder, I could also upload it. This is a very weird issue, because once I deleted the region files of the corrupted dungeons, they regenerated fine, so this can't be a mod conflict.

The world can be found here http://www.mediafire.com/download/mv8t8a85u2l65od/creeperman8362.7z and is in the corrupted Diona dungeon. Have fun!

**Comment by SteveKunG** [comment]
OK. You need to update More Planet to 1.3.1 and delete all old region files

**Comment by Creeperman8362** [comment]
OK, I will try to reproduce the glitch in 1.3.1. Maybe something tripped up in the original generation and it duplicated onto the other planets? IDK.

**Comment by Creeperman8362** [comment]
Deleted affected region files and updated to 1.3.1. Issue seems to be fixed.

**Comment by SteveKunG** [comment]
Okay. Thanks for testing. :)
