### ISSUE TITLE
conflict mods MORE PLANETS MOD v.1.2.9?

### ISSUE THREAD

**Issue by SvEgiiVEteR** [SteveKunG/More-Planets#54]
moreplanets
25,potion.infected.gas,stevekung.mods.moreplanets.planets.nibiru.potion.InfectedGasEffect
26,potion.chemical,stevekung.mods.moreplanets.planets.kapteynb.potion.ChemicalEffect
27,potion.emp,stevekung.mods.moreplanets.planets.diona.potion.EMPEffect
28,potion.icy_poison,stevekung.mods.moreplanets.planets.kapteynb.potion.IceCrystalEffect
AND
hungeroverhaul
27,potion.wellfedPotion,iguanaman.hungeroverhaul.potion.PotionWellFed

after installing moreplanets potion 27 missing

**Comment by SteveKunG** [comment]
Latest hotfix. I have already fix potion reflector. Did you have crash report or something?

**Comment by SvEgiiVEteR** [comment]
thank
no. breakage was not, but that was lost
potion.wellfedPotion, iguanaman.hungeroverhaul
it was not in the dump.
possible bug that mod. provided that Potion other mods are placed automatically.
but I was able to fix it ...
but add the ability to manually set the Potion would be good.
because sometimes auto does not work properly

**Comment by SteveKunG** [comment]
Good news. I fixed in the next version. You can using configuration for potion ids.
