### ISSUE TITLE
Crash creating Space Station

### ISSUE THREAD

**Issue by Haggle1996** [SteveKunG/More-Planets#62]
With minimal modset (NEI, Galacticraft 375, More Planets 1.3.0pre1), receive the following error when trying to create a space station on any planet that allows them (in a Tier 8 creative rocket):

http://pastebin.com/weHa3jv3

**Comment by SteveKunG** [comment]
Hmm. I'm not sure. What is TeleDimension mod?

**Comment by SteveKunG** [comment]
Please re-open if this issue still happen.

**Comment by Haggle1996** [comment]
Just FYI, this was the same dimension -11 issue. Changing all the More Planets dimension ID's to -2000+ fixed the problem.

**Comment by Haggle1996** [comment]
Though I can't create space stations anywhere except for earth, even though the GUI suggests I can. Creating one on an alternative planet creates it instead at earth. Creating one on Diona will crash the game.

**Comment by SteveKunG** [comment]
OK. Please try 1.3.0 Pre-2.
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2358057-more-planets-mod-v-1-3-0-pre-1-galacticraft-add-on?page=27#c532

**Comment by SteveKunG** [comment]
It still happen in 1.3.0 Pre-4?

**Comment by Haggle1996** [comment]
I will give it a whirl. 1.3.0 pre-2/3 were very crashy. :P

**Comment by SteveKunG** [comment]
I mean 1.3.0 Pre-4. Did you have a crash report?

**Comment by Haggle1996** [comment]
1.3.0 Pre-4 seems to be working fine. Thanks for updating it.
