### ISSUE TITLE
RuntimeException: Already decorating

### ISSUE THREAD

**Issue by apdjz** [SteveKunG/More-Planets#72]
It seems to be happening still. 

http://pastebin.com/kgpe46aV
More-Planets-1.7.10-1.3.0-Pre-4

**Comment by SteveKunG** [comment]
I'm not sure. But I see craftBukkit in the crash report. Can you testing in the singleplayer?

**Comment by apdjz** [comment]
I tried to get the crash and I failed.

**Comment by SteveKunG** [comment]
OK. I know.
I will release my mod at tomorrow. Thanks.

**Comment by SteveKunG** [comment]
Please test 1.3.0 Pre-6.

**Comment by apdjz** [comment]
Any chance you can make it able to runable on a server and allow  clients with the existing version be able to join?

**Comment by SteveKunG** [comment]
Can't run in the server? I understand a little bit.

**Comment by MJRLegends** [comment]
Yeah im getting the same crash see https://github.com/MJRLegends/Space-Astronomy-Feedback-/issues/141
