### ISSUE TITLE
Entity ID Conflict w/ GalaxySpace

### ISSUE THREAD

**Issue by jaller200** [SteveKunG/More-Planets#75]
Every time I try using both More-Planets and GalaxySpace together, I get a conflict between IDs, specifically the EvolvedEnderman ID. I just am wondering if you could somehow fix this - I would attempt myself but I am restricted because of the license.

Thanks!

- Jaller200

**Comment by SteveKunG** [comment]
![2558-12-20_22 55 05](https://cloud.githubusercontent.com/assets/6128413/11948718/a597550c-a8a9-11e5-90ec-37620d3f58fb.png)

It's working properly.

**Comment by SteveKunG** [comment]
Closed. Please re-open if this issue still happened.
