### ISSUE TITLE
Golden Field biome, slime spawn issue

### ISSUE THREAD

**Issue by BlackSymbol** [SteveKunG/More-Planets#78]
Slimes spawn at golden field biome and irritate a lot. My base is close to slime chunk, but nevertheless it's higher than level 40 and I'm not at swamp biome. Therefore I suggest that slimes either ignore minecraft way of slime spawn or its biome allowing them to do so. Is there a way to disable biome or slimes?

**Comment by SteveKunG** [comment]
Did you have any sceenshot in your world? I think it might be the Golden Field generated in the Overworld.

**Comment by BlackSymbol** [comment]
It is indeed in Overworld, forgot to mention it.

**Comment by SteveKunG** [comment]
Maybe biome id is conflict. Please change Golden Field biome id.

**Comment by BlackSymbol** [comment]
I cannot do that as saved world will then fail to load.

**Comment by SteveKunG** [comment]
No choice. You need to backup your map or regenerating a new chunk.

**Comment by BlackSymbol** [comment]
Would there exist some implementation in future versions allowing me to disable certain biomes / slimes (or is there a way to do it right now)? Also I was unable to find any description of biomes or slime spawn rules for the mod, if they exist provide me with a link please. You can close the issue.
