### ISSUE TITLE
Only pink candy cane tools craftable

### ISSUE THREAD

**Issue by Robijnvogel** [SteveKunG/More-Planets#82]
I can not craft tools in other colours than pink. The config setting: 
B:"Disable Multiple Candy Tools Recipe"=false
does not change this. This is sort of a feature request, but you may have been planning on implementing this already.

A a sidenote, what is that config option meant to do?

**Comment by SteveKunG** [comment]
I have changed config to this.

`    # If true, Candy Tools or Candy Bow or Poison Arrow can crafted by any type of candy cane.
    B:"Enable Multi Candy Tools Recipe"=true`

If you enable this to true, all candy cane can be use in the recipes
![2559-02-06_10 52 24](https://cloud.githubusercontent.com/assets/6128413/12864522/e35abfa2-ccbf-11e5-9a22-3c10a767583f.png)

**Comment by Robijnvogel** [comment]
I'll wait for the next version and see if it works.
(In the current version I test with only yellow parts and that didn't work.)

**Comment by SteveKunG** [comment]
You can testing this feature in 1.3.0 release.
