### ISSUE TITLE
server crash

### ISSUE THREAD

**Issue by Cronosus** [SteveKunG/More-Planets#87]
http://pastebin.com/7CDXLJSR
http://pastebin.com/ynENbYbm

**Comment by SteveKunG** [comment]
I'm not really sure. Did you try again and send the full game log?

**Comment by Cronosus** [comment]
ok, here
http://cronos.wz.cz/mc/err/latest.log

porting or with rocket to siriusb

**Comment by SteveKunG** [comment]
Maybe it cause by other mod. I think.

**Comment by Cronosus** [comment]
on crash report is this
tile.sirius_lava // stevekung.mods.moreplanets.planets.siriusb.fluids.BlockFluidSiriusLava

then i think, its problem with lava on siriusb

**Comment by Cronosus** [comment]
anyway, on siriusb is not Landing Pod or Baloons?

**Comment by SteveKunG** [comment]
Thanks for more info. I will take a look at this.

**Comment by Cronosus** [comment]
after update cauldon, crash little changed
http://pastebin.com/KqF3G67t
i think, have more info about it

**Comment by MJRLegends** [comment]
Im getting the same crash but with Fronos

**Comment by SteveKunG** [comment]
Please use KCauldron-1.7.10-1614.UNOFFICIAL. I think should be wait for KCauldron to fix something.

**Comment by Cronosus** [comment]
ok, ill try
thanks
