### ISSUE TITLE
T6 Rocket Launch Crash

### ISSUE THREAD

**Issue by SirWoofie** [SteveKunG/More-Planets#91]
Nibiru blocks seem to be a little buggy. I launched my Creative T6 Rocket from Polongnius and the game crashed 8 seconds before launch. (I use the creative rockets because I'm lazy)

Log File:
http://paste.ee/p/qsYtQ

Read from line 33530 and down. Thanks!
Edit: Log link got cut off at the Q. Fixed!

**Comment by MJRLegends** [comment]
@SirWoofie says Page Not Found when clicking on the link to the log you have provided

**Comment by SteveKunG** [comment]
You are using old version. Please use the latest (I will release the 1.3.1 Release for soon.)
