### ISSUE TITLE
Broken Dungeon Spawners!! Fix already found!

### ISSUE THREAD

**Issue by MJRLegends** [SteveKunG/More-Planets#92]
See https://github.com/micdoodle8/Galacticraft/issues/2076
This seems to be broken in your addon to @SteveKunG as it was in my addon and is in galacticraft

**Comment by SteveKunG** [comment]
I have already fix it.

https://github.com/SteveKunG/More-Planets/blob/1.7.10/src/main/java/stevekung/mods/moreplanets/core/worldgen/feature/WorldGenSpaceDungeons.java#L198-L217

**Comment by MJRLegends** [comment]
Fair enough :P

**Comment by SteveKunG** [comment]
Oops. Not fixed yet. Wrong file. :v

**Comment by MJRLegends** [comment]
@SteveKunG oh ok :P

**Comment by MJRLegends** [comment]
Please could you try and get a update out ASAP, so I can include it in my next update for my mod pack

**Comment by SteveKunG** [comment]
Hm? What is ASAP?

**Comment by vagaprime** [comment]
ASAP=as soon as possible
