### ISSUE TITLE
[Urgent] Server crashes when going to planets!!

### ISSUE THREAD

**Issue by MJRLegends** [SteveKunG/More-Planets#95]
When a player was launching to a few different planets he crashed the server with these crashes,

[crash-2016-02-14_00.09.01-server.txt](https://github.com/SteveKunG/More-Planets/files/129987/crash-2016-02-14_00.09.01-server.txt)
[crash-2016-02-14_17.20.26-server.txt](https://github.com/SteveKunG/More-Planets/files/129988/crash-2016-02-14_17.20.26-server.txt)
[crash-2016-02-14_18.30.18-server.txt](https://github.com/SteveKunG/More-Planets/files/129992/crash-2016-02-14_18.30.18-server.txt)
[crash-2016-02-14_18.34.49-server.txt](https://github.com/SteveKunG/More-Planets/files/129989/crash-2016-02-14_18.34.49-server.txt)
[crash-2016-02-14_18.38.01-server.txt](https://github.com/SteveKunG/More-Planets/files/129990/crash-2016-02-14_18.38.01-server.txt)
[crash-2016-02-14_18.41.43-server.txt](https://github.com/SteveKunG/More-Planets/files/129991/crash-2016-02-14_18.41.43-server.txt)
When generating new chunks....

Its crashing the hell out my server :(

im using KCauldron-1.7.10-1614.188
and latest More Planets and Galacticraft 1.7-3.0.12.440

**Comment by SteveKunG** [comment]
http://pastebin.com/px0T8eR0

I testing with KCauldron without any mod and found this crash. I think it's not my mod issue. (Maybe)

**Comment by MJRLegends** [comment]
@SteveKunG i doesnt happen with any other dimension and it only really happens 24/7 on Sirius B the others are just now and again

**Comment by SteveKunG** [comment]
That's happen in the old version of the KCauldron?

**Comment by MJRLegends** [comment]
@SteveKunG not sure because no one went to that planet in till now

**Comment by MJRLegends** [comment]
@SteveKunG right so i downgraded to KCauldron-1.7.10-1614.UNOFFICIAL and its seems fine and no crashes

**Comment by SteveKunG** [comment]
OK. Thanks for information!

**Comment by MJRLegends** [comment]
btw it still seems to be broken in latest version of KCauldron (v1614.200)

**Comment by MJRLegends** [comment]
Also i've reported it to the Kcauldron people see https://gitlab.prok.pw/KCauldron/KCauldron/issues/385
