### ISSUE TITLE
Can't reach Jupiter and its SS

### ISSUE THREAD

**Issue by nullg** [SteveKunG/More-Planets#96]
Hi, I love your mod a lot. I just found that I can't reach Jupiter and Jupiter space station for some reasons. It's kind of weird as a clickable button for Jupiter on GC map has been turned to green compare to the other yet unreachable planets like Saturn and etc are in red. Tried with deleting all configs including GC itself, removing other mods, or using some different versions of Forge as starting at 1291 to 1558 and 1614 as well, but none of them has worked. I'm attaching both screenshot and FML log. While else people haven't met the issue, I must be doing something wrong unexpectedly though... I appreciate if you could look into this. Thank you.

Galacticraft - 3.0.12.441
MorePlanets - 1.3.0 (also tried Pre-6)

http://pastebin.com/KrwEyAgD
 As a part of the log, it looks to me successfully registering Jupiter.
/////////////////
[15:24:30] [Server thread/INFO] [Galacticraft/GalacticraftCore]: Registered Dimension: -5000
[15:24:30] [Server thread/INFO] [FML/GalacticraftCore]: Loading dimension -5000 (New World) 
/////////////////

http://i.imgur.com/M6ihndf.png
Screenshot of GC galaxy map

**Comment by SteveKunG** [comment]
OK. Fixed in the next version. Thank you!
Note : I'm not recommended to explore the Jupiter :p
