### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by johnfg12** [SteveKunG/More-Planets#99]
[crash-2016-02-22_17.24.18-client.txt](https://github.com/SteveKunG/More-Planets/files/141053/crash-2016-02-22_17.24.18-client.txt)

java.lang.NoClassDefFoundError: stevekung/mods/moreplanets/core/items/ItemTier2ThermalPadding
this issue occours when loading with this mod installed

**Comment by MJRLegends** [comment]
Update your galacticraft!!

**Comment by SteveKunG** [comment]
Require 442 : ci.micdoodle8.com/job/Galacticraft-1.7/442/

**Comment by johnfg12** [comment]
is that version stable?

**Comment by SteveKunG** [comment]
No. But my mod require that and its seem to be no other issue occur.

**Comment by johnfg12** [comment]
ok thanks :D love the responce btw
